apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: default
  labels:
    service: rabbitmq
    provider: rabbitmq
spec:
  ports:
  - port: 15672
    targetPort: 15672
    protocol : TCP
    name : admin-port
  - port: 5672
    targetPort: 5672
    protocol : TCP
    name : default
  - port: 4369
    targetPort: 4369
    protocol : TCP
    name : epmd-port
  - port: 25672
    targetPort: 25672
    protocol : TCP
    name : dist-port

  selector:
    provider: rabbitmq
