apiVersion: v1
kind: ReplicationController
metadata:
  name: rabbitmq
  namespace: default
  labels:
    service: rabbitmq
    provider: rabbitmq
spec:
  replicas: 1
  template:
    metadata:
      labels:
        provider: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        env:
          - name: RABBITMQ_ERLANG_COOKIE
            value: 'secretcookiehere'
          # - name : RABBITMQ_DEFAULT_USER
          #   value : user
          # - name : RABBITMQ_DEFAULT_PASS
          #   value : password
          # - name : HOSTNAME
          #   value : rmq-node-1-svc

        ports:
          - containerPort: 15672
            targetPort: 15672
            protocol : TCP
            name : admin-port
          - containerPort: 5672
            targetPort: 5672
            protocol : TCP
            name : default
          - containerPort: 4369
            targetPort: 4369
            protocol : TCP
            name : epmd-port
          - containerPort: 25672
            targetPort: 25672
            protocol : TCP
            name : dist-port
