apiVersion: v1
kind: Service
metadata:
  name: postgresql-gitlab
  labels:
    name: postgresql-gitlab
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
  selector:
    name: postgresql-gitlab
