apiVersion: v1
kind: Service
metadata:
  name: koding
  namespace: default
  labels:
    name: koding
    service: koding
    app: koding
spec:
  type: LoadBalancer
  selector:
    name: koding
  ports:
    - name: http
      port: 80
      targetPort: 80

