apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: default
  labels:
    service: postgres
spec:
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    service: postgres
status:
  loadBalancer: {}

