apiVersion: v1
kind: ReplicationController
metadata:
  name: redis
  labels:
    provider: redis
spec:
  replicas: 1
  selector:
    name: redis
    mode: standalone
    provider: redis
  template:
    metadata:
      name: redis
      labels:
        name: redis
        mode: standalone
        provider: redis
        app: redis
    spec:
      containers:
      - name: redis
        image: kubernetes/redis:v1
        env:
        - name: MASTER
          value: "true"
        ports:
        - name: redis
          containerPort: 6379
        volumeMounts:
        - mountPath: /redis-master-data
          name: data
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          timeoutSeconds: 1
      volumes:
        - name: data
          emptyDir: {}
